# Grouping all tweets by their users

In [1]:
# import bz2
# from typing import List, Union
# from glob import glob
# from os import path
# from pathlib import Path
# import json
# from glob import glob
# from os import path
# from typing import List

# import dask.bag as db

In [1]:
from dask.distributed import Client

client = Client(dashboard_address='0.0.0.0:6784')
client

In [3]:
from murpheus import DataLoading

In [4]:
dl = DataLoading()
dl

In [12]:
bags_of_tweets = dl._get_twitter_data_as_bags(file_find_expression = '/mnt/c/Users/aliab/Google_Drive/Work/Projects/SMPA/data/**/*.bz2')
bags_of_tweets.take(1)

({'created_at': 'Mon Jun 01 06:29:00 +0000 2020',
  'id': 1267342365427032065,
  'id_str': '1267342365427032065',
  'text': '„ÉÄ„É´„Åô„Åé„Å¶ÂÖ®Ë∫´„ÅÆÂäõÊäú„ÅÑ„Å¶„Çã„ÅóÂá∫„Åã„Åë„Çã„Åë„Å©Êê∫Â∏Ø„Åó„ÅãÊâã„Å´„Åó„Å¶„Å™„ÅÑ',
  'source': '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
  'truncated': False,
  'in_reply_to_status_id': None,
  'in_reply_to_status_id_str': None,
  'in_reply_to_user_id': None,
  'in_reply_to_user_id_str': None,
  'in_reply_to_screen_name': None,
  'user': {'id': 1174569236292755458,
   'id_str': '1174569236292755458',
   'name': '„Åì„ÅÜ„ÇÑüí∏ÈáëÊ¨†üí∞',
   'screen_name': 'Ko_uya_15',
   'location': '„ÅäÂà•„Çå„ÅØ„Éñ„É≠Ëß£',
   'url': None,
   'description': '„ÅÜ„Åó„Åï„Åõ„ÇíËá™ÂàÜ„ÅÆ„Éö„Éº„Çπ„ÅßÁÆ±Êé®„Åó„Å™ÈõëÂ§ö/Áµµ„ÇíÊ®°Á¥¢‰∏≠ü§î/Subüîë„Äê@kouya_sub_15„Äë',
   'translator_type': 'none',
   'protected': False,
   'verified': False,
   'followers_count': 264,
   'friends_count': 120,
   'listed_count': 9,
   'favourites_count': 5146,
   'statuses_count': 4588,
   'created_at': 'Thu Sep 19 06:21:52 +0000 2019',
   'utc_offset': None,
   'time_zone': None,
   'geo_enabled': False,
   'lang': None,
   'contributors_enabled': False,
   'is_translator': False,
   'profile_background_color': 'F5F8FA',
   'profile_background_image_url': '',
   'profile_background_image_url_https': '',
   'profile_background_tile': False,
   'profile_link_color': '1DA1F2',
   'profile_sidebar_border_color': 'C0DEED',
   'profile_sidebar_fill_color': 'DDEEF6',
   'profile_text_color': '333333',
   'profile_use_background_image': True,
   'profile_image_url': 'http://pbs.twimg.com/profile_images/1266001779273035777/I9wMSGcf_normal.jpg',
   'profile_image_url_https': 'https://pbs.twimg.com/profile_images/1266001779273035777/I9wMSGcf_normal.jpg',
   'profile_banner_url': 'https://pbs.twimg.com/profile_banners/1174569236292755458/1590477916',
   'default_profile': True,
   'default_profile_image': False,
   'following': None,
   'follow_request_sent': None,
   'notifications': None},
  'geo': None,
  'coordinates': None,
  'place': None,
  'contributors': None,
  'is_quote_status': False,
  'quote_count': 0,
  'reply_count': 0,
  'retweet_count': 0,
  'favorite_count': 0,
  'entities': {'hashtags': [], 'urls': [], 'user_mentions': [], 'symbols': []},
  'favorited': False,
  'retweeted': False,
  'filter_level': 'low',
  'lang': 'ja',
  'timestamp_ms': '1590992940657'},)

In [13]:
dataframe_of_tweets = bags_of_tweets.to_dataframe()
dataframe_of_tweets = dataframe_of_tweets[dataframe_of_tweets['lang'] == 'en']
dataframe_of_tweets

Dask DataFrame Structure:
                 created_at     id  id_str    text  source truncated in_reply_to_status_id in_reply_to_status_id_str in_reply_to_user_id in_reply_to_user_id_str in_reply_to_screen_name    user     geo coordinates   place contributors is_quote_status quote_count reply_count retweet_count favorite_count entities favorited retweeted filter_level    lang timestamp_ms
npartitions=1411
                     object  int64  object  object  object      bool                object                    object              object                  object                  object  object  object      object  object       object            bool       int64       int64         int64          int64   object      bool      bool       object  object       object
                        ...    ...     ...     ...     ...       ...                   ...                       ...                 ...                     ...                     ...     ...     ...         ...     ...          ...             ...         ...         ...           ...            ...      ...       ...       ...          ...     ...          ...
...                     ...    ...     ...     ...     ...       ...                   ...                       ...                 ...                     ...                     ...     ...     ...         ...     ...          ...             ...         ...         ...           ...            ...      ...       ...       ...          ...     ...          ...
                        ...    ...     ...     ...     ...       ...                   ...                       ...                 ...                     ...                     ...     ...     ...         ...     ...          ...             ...         ...         ...           ...            ...      ...       ...       ...          ...     ...          ...
                        ...    ...     ...     ...     ...       ...                   ...                       ...                 ...                     ...                     ...     ...     ...         ...     ...          ...             ...         ...         ...           ...            ...      ...       ...       ...          ...     ...          ...
Dask Name: getitem, 8466 tasks

In [14]:
list(dataframe_of_tweets.columns.values)

['created_at',
 'id',
 'id_str',
 'text',
 'source',
 'truncated',
 'in_reply_to_status_id',
 'in_reply_to_status_id_str',
 'in_reply_to_user_id',
 'in_reply_to_user_id_str',
 'in_reply_to_screen_name',
 'user',
 'geo',
 'coordinates',
 'place',
 'contributors',
 'is_quote_status',
 'quote_count',
 'reply_count',
 'retweet_count',
 'favorite_count',
 'entities',
 'favorited',
 'retweeted',
 'filter_level',
 'lang',
 'timestamp_ms']

In [15]:
sample = dataframe_of_tweets.head()
sample

,created_at,id,id_str,text,source,truncated,in_reply_to_status_id,in_reply_to_status_id_str,in_reply_to_user_id,in_reply_to_user_id_str,...,quote_count,reply_count,retweet_count,favorite_count,entities,favorited,retweeted,filter_level,lang,timestamp_ms
9,Mon Jun 01 06:29:00 +0000 2020,1267342365431382017,1267342365431382017,RT @isabelleprimave: DON'T feel bad that you c...,"<a href=""http://twitter.com/download/iphone"" r...",False,NaN,None,NaN,None,...,0,0,0,0,"{'hashtags': [], 'urls': [], 'user_mentions': ...",False,False,low,en,1590992940658
11,Mon Jun 01 06:29:00 +0000 2020,1267342365427150849,1267342365427150849,There's beauty at the end of the struggle. Jus...,"<a href=""http://twitter.com/download/android"" ...",False,NaN,None,NaN,None,...,0,0,0,0,"{'hashtags': [], 'urls': [], 'user_mentions': ...",False,False,low,en,1590992940657
14,Mon Jun 01 06:29:00 +0000 2020,1267342365452206080,1267342365452206080,RT @shockWilliams20: It‚Äôs past midnight but so...,"<a href=""http://twitter.com/download/android"" ...",False,NaN,None,NaN,None,...,0,0,0,0,"{'hashtags': [], 'urls': [], 'user_mentions': ...",False,False,low,en,1590992940663
16,Mon Jun 01 06:29:00 +0000 2020,1267342365431181312,1267342365431181312,RT @juliacarriew: A decent number of Facebook ...,"<a href=""http://twitter.com/download/iphone"" r...",False,NaN,None,NaN,None,...,0,0,0,0,"{'hashtags': [], 'urls': [], 'user_mentions': ...",False,False,low,en,1590992940658
17,Mon Jun 01 06:29:00 +0000 2020,1267342365439729664,1267342365439729664,RT @Mohamed34018605: Retweet üîÉ üîÉ üîÉ \n#ŸÖŸÇÿßÿ∑ÿπŸá_ÿß...,"<a href=""http://twitter.com/download/android"" ...",False,NaN,None,NaN,None,...,0,0,0,0,"{'hashtags': [{'text': 'ŸÖŸÇÿßÿ∑ÿπŸá_ÿßŸÖÿ™ÿ≠ÿßŸÜÿßÿ™_3ÿ´', '...",False,False,low,en,1590992940660

In [16]:
dataframe_of_tweets['user_name'] = dataframe_of_tweets['user'].apply(lambda x: x['screen_name'], meta=str)
dataframe_of_tweets

Dask DataFrame Structure:
                 created_at     id  id_str    text  source truncated in_reply_to_status_id in_reply_to_status_id_str in_reply_to_user_id in_reply_to_user_id_str in_reply_to_screen_name    user     geo coordinates   place contributors is_quote_status quote_count reply_count retweet_count favorite_count entities favorited retweeted filter_level    lang timestamp_ms user_name
npartitions=1411
                     object  int64  object  object  object      bool                object                    object              object                  object                  object  object  object      object  object       object            bool       int64       int64         int64          int64   object      bool      bool       object  object       object    object
                        ...    ...     ...     ...     ...       ...                   ...                       ...                 ...                     ...                     ...     ...     ...         ...     ...          ...             ...         ...         ...           ...            ...      ...       ...       ...          ...     ...          ...       ...
...                     ...    ...     ...     ...     ...       ...                   ...                       ...                 ...                     ...                     ...     ...     ...         ...     ...          ...             ...         ...         ...           ...            ...      ...       ...       ...          ...     ...          ...       ...
                        ...    ...     ...     ...     ...       ...                   ...                       ...                 ...                     ...                     ...     ...     ...         ...     ...          ...             ...         ...         ...           ...            ...      ...       ...       ...          ...     ...          ...       ...
                        ...    ...     ...     ...     ...       ...                   ...                       ...                 ...                     ...                     ...     ...     ...         ...     ...          ...             ...         ...         ...           ...            ...      ...       ...       ...          ...     ...          ...       ...
Dask Name: assign, 12699 tasks

In [18]:
dataframe_of_tweets.shape[0].compute()

1974416

In [ ]:
%%timeit
df.groupby('user_name').apply(lambda x: list(x['entities']), meta=list).to_csv('user_data_all/*.csv')

distributed.nanny - WARNING - Restarting worker